name: Build and Tag

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - main
      - stable
  workflow_dispatch:

jobs:
  build-scan-push:
    uses: r0ps3c/gh-shared-workflows/.github/workflows/docker-build-scan-push.yml@c6ef69d22ab5c31b04437b8c5ee27be005df3d3c # main
    with:
      image-ref: unbound-network:main
      version-extract-command: "apk info unbound 2>/dev/null | grep '^unbound-' | head -1 | cut -d- -f2 | cut -dr -f1"
      test-command: make test-structure && make test-standalone && make test-integration
    secrets: inherit
